language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: JIMCVGjvhLZi7jNPoGDqAc53GvNyx0k0AcEiSZz0DaoGBPMjgx/j9/pyzqpBZWAzMmqszJDGSk3Ff5bUHudMHpdt0sgVCld1cwhYeYJuuNjzKd1uHEZlK8pDefAqIfDaLgeoDepny0mq2m3OZB++o+VUqcowNmg8iiBeG5kWGribd4UlPIh/cY1YBq92LkUS1E7S5emi5WbN0WMCVOl55xXeHP6XI8y8ZvpLrIYtwYsmeDC6MrfSFeG0Ko/kgs4vo8AYCxDVz9ZdQPhcaeeY/lZLcsNumk4qIADsl5R6E/ObwDiQXYB49SWAsg2sLkGmyE2kR93W9Jk+kyrPSfxGp3Vn7yGGP10T/nOiP3nRp5ldhkfopwChHYmjVTMaDoCkW+YGVjxz4NF3kO1Kot57ziIdwJUK9AJl5ACQNSEqcr0pNqVlFR86YdxBlEg8ugXlKsAj2d3WOXTGOB0gFcHjymIy/AcntiPHlI7SzS9Jl0CWByfGItDlXqmE4Qif+BkhIR+VXwh6kT1PZ60SoawB8fYoxd4rJggLGQCNsh/nAJS1f1CwYlg0beSZoRrHRFCQzQ8m7uBz/2yAWBg14JswGVO02szTPu7siSljC0/JHYCBFlFqCNPGUEA2HDaBkW/WNhoTvZ0XQKWkdbRfrZNWqsU3fMi7dv3APSi9BF0WO6U=
